import path from 'node:path';
import dotenv from 'dotenv';
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });
dotenv.config({ path: path.resolve(process.cwd(), '.env') });
import fg from 'fast-glob';import fs from 'node:fs/promises';import {PrismaClient} from '@prisma/client';import {request} from 'undici';
const db=new PrismaClient();const repo=(process.env.GITHUB_REPOSITORY_URL||'').replace(/\.git$/,'');
async function sync(){const u=new URL(repo);const parts=u.pathname.split('/').filter(Boolean);const owner=parts[0],name=parts[1];if(!owner||!name)throw Error('Invalid GITHUB_REPOSITORY_URL');const api=`https://api.github.com/repos/${owner}/${name}/git/trees/HEAD?recursive=1`;const headers:any={'user-agent':'VoidCriptUI-Platform'};if(process.env.GITHUB_TOKEN)headers.authorization=`Bearer ${process.env.GITHUB_TOKEN}`;const r=await request(api,{headers});if(r.statusCode>=400)throw Error(`GitHub ${r.statusCode}`);const tree:any=await r.body.json();const files=(tree.tree||[]).filter((x:any)=>x.type==='blob');const sha=tree.sha;await db.repositorySnapshot.create({data:{repoUrl:repo,ref:'HEAD',commitSha:sha,fileCount:files.length,manifest:files.map((x:any)=>x.path),successful:true}});console.log(`GitHub sync: ${files.length} files, ${sha}`)}
async function qaLocal(){const root=process.env.QA_ROOT||path.resolve(__dirname,'../../..');const files=await fg(['**/*.lua','**/*.luau'],{cwd:root,ignore:['node_modules/**','.git/**']});const findings:any[]=[];for(const f of files){const text=await fs.readFile(path.join(root,f),'utf8');if(text.trim().length===0)findings.push({status:'ERROR',severity:'high',file:f,message:'Empty source file',confidence:'high'});if(/\bTODO\b|\bFIXME\b/.test(text))findings.push({status:'WARNING',severity:'low',file:f,message:'TODO/FIXME marker detected',confidence:'high'});if(/while\s+task\.wait/.test(text))findings.push({status:'WARNING',severity:'medium',file:f,message:'Polling loop pattern detected',confidence:'medium'});if(/RenderStepped/.test(text))findings.push({status:'INFO',severity:'low',file:f,message:'RenderStepped usage detected',confidence:'high'})}const score=Math.max(0,100-findings.filter(x=>x.status==='ERROR').length*10-findings.filter(x=>x.status==='WARNING').length*2);await db.qaRun.create({data:{status:'completed',score,findings}});console.log(`QA: ${files.length} Lua files, ${findings.length} findings, score ${score}`)}
(async()=>{try{if(process.argv.includes('--qa'))await qaLocal();else await sync()}catch(e){console.error(e);process.exitCode=1}finally{await db.$disconnect()}})();
